### ISSUE TITLE
Tracking: full LN interoperability

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/lnp-node#45]
1. Connectivity:
    - [x] BOLT-8: Brontide encryption protocol & connectivity
    - [x] BOLT-1: lightning serialization of data types
    - [x] BOLT-1: TLV type serialization
    - [x] BOLT-1: peer protocol (`init`, `ping` & `pong` exchange)
    - [x] BOLT-9: channel feature flags
2. Channel establishment
    - [x] BOLT-3: Key derivation
    - [x] BOLT-3: Proper tx structure generation
    - [x] BOLT-2: Outbound channel opening
    - [ ] (WIP) BOLT-2: Inbound channel acceptance
    - [ ] BOLT-2: Channel re-establishment
3. HTLC payments
    - [x] (untested) BOLT-3 HTLC outputs and transactions
    - [ ] BOLT-7: Onion encoding
    - [ ] BOLT-7: Gossip protocol
    - [ ] BOLT-7: Route computing
    - [ ] BOLT-2: HTLC P2P messaging
    - [ ] BOLT-2: Commitment transaction updates
    - [ ] (partial) BOLT-11: invocing
4. Channel closing
    - [ ] BOLT-2: Cooperative closing
    - [ ] Uncooperative closing
    - [ ] Penalty execution
