### ISSUE TITLE
Tracking: node operations

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/lnp-node#46]
1. Setup
    - [x] Keys & wallets generation
    - [x] Network selection
    - [x] Threaded daemons / library builds
    - [ ] Configuration file with `configure_me`
2. Persistence
    - [x] Node keys
    - [x] Node funding wallet
    - [ ] Persisting provisionary channel
    - [ ] Persisting channel state
    - [ ] Persisting channel history
    - [ ] Persisting gossip database
3. Robustness
    - [x] Correctly handling channel_id changes (from temporary to persistent)
    - [ ] Re-launching `channeld` in case of crashes
    - [ ] Re-establishing `channeld`-`peerd` connectivity
4. Transactions
    - [x] Signing wallet
    - [ ] (partial) LNP-specific PSBT custom keys
    - [ ] Tracking funding tx
    - [ ] Tracking channel closings
